name: Production

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  production:
    name: Production
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel (Production)
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_vLDYhOxLmchIKn4wYKStFlglaji2/IohYnGbnwu
